# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileGame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileGame

  pod 'Firebase/Core'


  target 'MobileGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileGameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
